name: production-integration-wf
on:
  pull_request:
    branches:
      - main
jobs:
  Production-linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{gethub.ref}}
      - name: Linting of HTML and CSS Files
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
  Production-build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{gethub.ref}}
      - name: Build using Parcel 
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
  Production-test-job:
    needs: Production-build-job
    runs-on: ubuntu-latest
    steps: 
      - name: Run Unit Tests (Jest)
        run: npm test -- --coverage
      - name: Run ESLint (Code Quality Check)
        run: npx eslint .--ext .js,.jsx,.ts,.tsx
      - name: Notify Team
        run: echo " All lint, build,tests completed successfully"